### ISSUE TITLE
please blacklist nouveau driver

### ISSUE THREAD

**Issue by pescobar** [NVIDIA/ansible-role-nvidia-driver#44]
is there any reason why this role doesn't include a task like this?

```
- name: Blacklist the nouveau driver module                                                                                                                                                                                            
  community.general.kernel_blacklist:                                                                                                                                                                                                  
    name: nouveau                                                                                                                                                                                                                      
    state: present 
```

**Comment by TidyData** [comment]
seems ansible has this built in already

```yaml
    - name: Blacklist the nouveau driver module
      become: yes
      kernel_blacklist:
        name: nouveau
        state: present
```
