### ISSUE TITLE
Support for Debian

### ISSUE THREAD

**Issue by fuog** [NVIDIA/ansible-role-nvidia-driver#67]
Hi there,

i wanted to thank you for the nice ansible role. Unfortunately Debian does not seem to be officially supported. But I managed it with a bit of variable overriding.
I would be happy if debian would be officially supported.  Until then, maybe this will help someone who uses debian to use this role anyway.

```yaml
# my playbook
.....
  roles:
    - role: unix-basics
      tags: unix-basics
    - role: xanmanning.k3s
      tags: k3s
    - role: nvidia.nvidia_driver  # should run after cluster install
      vars:
        # See https://github.com/NVIDIA/ansible-role-nvidia-driver#role-variables
        nvidia_driver_ubuntu_cuda_repo_baseurl: 'https://developer.download.nvidia.com/compute/cuda/repos/debian11/x86_64'  # enforced 'debian11'
        nvidia_driver_ubuntu_install_from_cuda_repo: yes
        nvidia_driver_persistence_mode_on: yes
        ansible_distribution: Ubuntu  # forcing in to the ubuntu part of the role
      when: ansible_hostname == 'k3s-worker1'  # we only have ONE node with NVIDIA
      tags:
        - nvidia
....
```
